### PR TITLE
ADD: Obol Charon Service, EventListener via IPC

### PR DESCRIPTION
**Pull request by NeoPlays**
### Obol Charon Service
this marks the first step for the integration of the complete obol service

### EventListener via IPC
added boilerplate code for EventListener which listen to events emited from the backend

`background.js`
```
//get right BrowserWindow object
let allWindows = BrowserWindow.getAllWindows()
let mainWindow = allWindows[allWindows.length - 1] // the last window is always the main (at least in our case)
mainWindow.webContents.send('ChannelToListenOn', data)
```

`SomeComponent.vue`
```
import ControlService from "@/store/ControlService";

// start listener (in created for example)
ControlService.addListener('ChannelToListenOn', this.someFunction)

// remove listener (in beforeUnmount() for example)
ControlService.removeListener('ChannelToListenOn', this.someFunction)

// function that updates this.counter in real time
someFunction(event, data){
  this.counter = data
}
```

### CODE REVIEW

**Review by daverolo — APPROVED** [review]
LGTM 🍄 🦸‍♂️ 🚀

**Comment by OisinKyne** [comment]
Hey guys, loving that you guys are integrating Obol ❤️  One small heads up, the Icons you guys have outlined, are our older versions (note the shape of the loop is much more asymetrical/fish like), you can get copies of our latest icon [here](https://blog.obol.tech/branding). Let me know if you need any other resolutions/formats. :D

**Comment by daGscheid** [comment]
> Hey guys, loving that you guys are integrating Obol ❤️ One small heads up, the Icons you guys have outlined, are our older versions (note the shape of the loop is much more asymetrical/fish like), you can get copies of our latest icon [here](https://blog.obol.tech/branding). Let me know if you need any other resolutions/formats. :D

Hey 👋 
Already took care of it (I think)
These are the three icons we will use inside of Stereum, I changed them according to the page you linked: 

OBOL SSV Network
OBOL SSV
OBOL SSV Network - Service - Circle


Lets us know if these better fit your brand, or we should change something else! ❤️ 

--- 

P.S.: because I stumbled upon it, there is a hex color code on there that doesn't work:

image

(Probably a zero, or? Didn't use it just to be sure 😄 )

**Comment by OisinKyne** [comment]
> P.S.: because I stumbled upon it, there is a hex color code on there that doesn't work:
> 
> image
> 
> (Probably a zero, or? Didn't use it just to be sure 😄 )

[Fixed](https://blog.obol.tech/branding/)! Danke

**Pull request merged**
