### PR TITLE
Update Missing Translations

### PR DESCRIPTION
**Pull request by daGscheid**
Solving #862

### CODE REVIEW

**Comment by mabasian** [comment]
Persian language need some edition. Should I approve it before or after edit? @daGscheid

**Comment by daGscheid** [comment]
> Persian language need some edition. Should I approve it before or after edit? @daGscheid

After I'd say

**Comment by mabasian** [comment]
> > Persian language need some edition. Should I approve it before or after edit? @daGscheid
> 
> After I'd say

Could you please change the status of the pull request to draft? I will clone your branch tomorrow and make the necessary edits. 😄

**Comment by mabasian** [comment]
✅ Done!

**Review by mabasian — APPROVED** [review]
LGTM 🚀

**Pull request merged**
