### PR TITLE
ADD: Fee Recipient via API

### PR DESCRIPTION
**Pull request by NeoPlays**
waiting for implementation on client side

- [x] [Lighthouse](https://github.com/sigp/lighthouse/issues/3173)
- [x] [Prysm](https://github.com/prysmaticlabs/prysm/pull/10850)
- [x] [Nimbus](https://github.com/status-im/nimbus-eth2/pull/3864)
- [x] [Teku](https://github.com/ConsenSys/teku/issues/6050)

### CODE REVIEW

**Comment by maxbehzadi82** [comment]
@NeoPlays which part of the fee recipient r u working on? 
Screenshot 2022-08-06 at 20 16 05

**Comment by NeoPlays** [comment]
> @NeoPlays which part of the fee recipient r u working on? Screenshot 2022-08-06 at 20 16 05

functionality of this thing but the teku client hasn't implemented it yet.. actually it's done already 😅

**Comment by NeoPlays** [comment]
i took out the frontend implementation to avoid future conflicts.
I tested the import on:

- [ ] Teku - Response: ""
- [ ] Lighthouse - Response: null
- [ ] Nimbus - Response: ""
- [ ] Prysm - Response: ""

the imports where successful for all clients where i was able to check the fee recipient in a file
i couldn't find any file for prysm but the api request didn't fail either
I also tested restarting the containers to check if the `--validators-proposer-default-fee-recipient` would overright the api import and they don't so the api has higher priority just like some docs state

**Comment by stefa2k** [comment]
lgtm, but somebody with JS experience should look over it too

**Review by mabasian — APPROVED** [review]
lg

**Pull request merged**
