### PR TITLE
ADD: current slot status in backend

### PR DESCRIPTION
**Pull request by gbayasgalan**
issue: https://github.com/stereum-dev/ethereum-node/issues/673

Status of slot(s) which are belonging to current, justified and finalized epochs (backend), also frontend:)

### CODE REVIEW

**Comment by gbayasgalan** [comment]
@mabasian - please work on this branch to complete UI :)

**Comment by mabasian** [comment]
Done, please review and let me know if it needs more work!

**Comment by gbayasgalan** [comment]
> Done, please review and let me know if it needs more work!

small bug on gnosis chain, the proposed Block shows 32 slots

**Review by mabasian — APPROVED** [review]
LGTM👍🏼

**Pull request merged**
