### PR TITLE
Update Translations

### PR DESCRIPTION
**Pull request by daGscheid**
- Update Translation for:
   - Arabic
   - Czech
   - Spanish
   - German 
   - Bulgarian

### CODE REVIEW

**Review by daverolo — DISMISSED** [review]
LGTM 🚀

**Comment by daGscheid** [comment]
@mabasian should probably merge https://github.com/stereum-dev/ethereum-node/pull/1691 first, or?

**Comment by mabasian** [comment]
> @mabasian should probably merge #1691 first, or?

It has no conflict 🚀

**Comment by daGscheid** [comment]
Now it got no conflict, hopefully it stays that way 😄

**Review by mabasian — APPROVED** [review]
LGTM 🚀

**Pull request merged**
